version: "3.7"

services:
  server:
    build:
      target: development
    volumes:
      - ./server:/usr/src/covid-19-spain-server
      - /usr/src/covid-19-spain-server/node_modules

  frontend:
    build:
      target: development
    # Workaround for https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/covid-19-spain-frontend
    ports:
      - "4200:4200"
