version: "3.7"

services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "3000:3000"

  database:
    image: mongo:bionic

  frontend:
    build:
      context: ./frontend
