version: "3.7"

services:
  server:
    build:
      target: development
    volumes:
      - ./server:/usr/src/covid-19-spain-server
      - /usr/src/covid-19-spain-server/node_modules
    ports:
      - "3000:3000"
