version: "3.7"

services:
  server:
    build: ./server
    env_file: ./server/.env
    ports:
      - "3000:3000"
    command: ["wait-for-it", "database:27017", "--", "npm run start:prod"]

  database:
    image: mongo:bionic
