version: "3.7"

services:
  server:
    build:
      target: production

  database:
    volumes:
      - ./data:/data/db

  frontend:
    build:
      target: production
    env_file:
      - ./frontend/.env.production
    ports:
      - "80:80"
