name: GitHub CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build server image
        working-directory: ./server
        run: docker build .

      - name: Build frontend image
      working-directory: ./frontend
      run: docker build .
